/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartAll: typeof import('./src/components/Chart/chart-all.vue')['default']
    ChatWidget: typeof import('./src/components/ChatBot/chat-widget.vue')['default']
    CompareReports: typeof import('./src/components/SimulationReport/CompareReports.vue')['default']
    DetailedReport: typeof import('./src/components/SimulationReport/DetailedReport.vue')['default']
    ErrorPopups: typeof import('./src/components/ErrorPopups.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logs: typeof import('./src/components/Logs.vue')['default']
    LogViewer: typeof import('./src/components/Log/LogViewer.vue')['default']
    ModuleToolbar: typeof import('./src/components/module-toolbar.vue')['default']
    Overview: typeof import('./src/components/SimulationReport/View/overview.vue')['default']
    PrintJobCreate: typeof import('./src/components/PrintJob/print-job-create.vue')['default']
    PrintJobs: typeof import('./src/components/PrintJobs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimulationReportGenerate: typeof import('./src/components/SimulationReport/simulation-report-generate.vue')['default']
    SimulationReportHistory: typeof import('./src/components/SimulationReport/simulation-report-history.vue')['default']
    SimulationReportListItem: typeof import('./src/components/SimulationReport/simulation-report-list-item.vue')['default']
    SimulationReports: typeof import('./src/components/SimulationReports.vue')['default']
    SimulationReportView: typeof import('./src/components/SimulationReport/simulation-report-view.vue')['default']
    SiteDashboard: typeof import('./src/components/SiteDashboard.vue')['default']
    SiteNavigationDrawer: typeof import('./src/components/SiteNavigationDrawer.vue')['default']
    WorkflowCreate: typeof import('./src/components/Workflow/workflow-create.vue')['default']
    WorkFlows: typeof import('./src/components/WorkFlows.vue')['default']
  }
}
