/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompareReports: typeof import('./src/components/SimulationReport/CompareReports.vue')['default']
    DetailedReport: typeof import('./src/components/SimulationReport/DetailedReport.vue')['default']
    ErrorPopups: typeof import('./src/components/ErrorPopups.vue')['default']
    PrintJobs: typeof import('./src/components/PrintJobs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimulationReportGenerate: typeof import('./src/components/SimulationReport/simulation-report-generate.vue')['default']
    SimulationReportHistory: typeof import('./src/components/SimulationReport/simulation-report-history.vue')['default']
    SimulationReports: typeof import('./src/components/SimulationReports.vue')['default']
    SiteDashboard: typeof import('./src/components/SiteDashboard.vue')['default']
    SiteNavigationDrawer: typeof import('./src/components/SiteNavigationDrawer.vue')['default']
    SubmitJobs: typeof import('./src/components/SubmitJobs.vue')['default']
    WorkFlows: typeof import('./src/components/WorkFlows.vue')['default']
  }
}
